version: '3.8'

services:
  backend:
    container_name: backend
    build:
      context: .
      dockerfile: ./backend/Dockerfile
    command: /start.sh
    volumes:
      - './backend/:/usr/src/backend'
      - 'static_volume:/usr/src/backend/staticfiles'
      - 'media_volume:/usr/src/backend/mediafiles'
    expose:
      - 8000
    env_file:
      - ./.env
    networks:
      - proxy-frontend-backend

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile
    volumes:
      - '/usr/src/frontend/node_modules'
      - './frontend:/usr/src/frontend'
      - 'static_volume:/usr/src/backend/staticfiles'
      - 'media_volume:/usr/src/backend/mediafiles'
    expose:
      - 8080
    depends_on:
      - backend
    networks:
      - proxy-frontend-backend

  proxy:
    container_name: proxy
    image: library/nginx:1.19.3-alpine
    ports:
      - '8000:80'
    depends_on:
      - frontend
    volumes:
      - './proxy/nginx.conf:/etc/nginx/nginx.conf:ro'
      - 'static_volume:/usr/src/backend/staticfiles'
      - 'media_volume:/usr/src/backend/mediafiles'
    networks:
      - proxy-frontend-backend


networks:
  proxy-frontend-backend:
    driver: bridge

volumes:
  static_volume:
  media_volume: